### ISSUE TITLE
Upgrade commons-dbcp2 and commons-pool2 libraries [PAXJDBC-158]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.jdbc#222]
**[Grzegorz Grzybek](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:9c7cd322-6f60-46ab-9235-bab9ac2f59f6)** created **[PAXJDBC-158](https://ops4j1.jira.com/browse/PAXJDBC-158)** 

---

**Fixed in:** 1.5.0, 1.4.6
Votes: 0, Watches: 1

**Comment by grgrzybek** [comment]
Fixed in 2ffbda6ca5365a6256623f53ed0330a17035d998.
