### ISSUE TITLE
Upgrade to fixed MariaDB JDBC driver when it comes out

### ISSUE THREAD

**Issue by grgrzybek** [ops4j/org.ops4j.pax.jdbc#230]
Waiting for:
* https://github.com/mariadb-corporation/mariadb-connector-j/pull/170
* https://jira.mariadb.org/browse/CONJ-867

**Comment by DrHackschnitzel** [comment]
Hi, 
both links who are mentioned in waiting for are fixed.
When will this Bug MariaDB issue #227 be fixed?

**Comment by grgrzybek** [comment]
Fixed and tested on `master` branch. I'll release soon (cc: @jbonofre)

**Comment by DrHackschnitzel** [comment]
sounds great. @grgrzybek thanks
