### ISSUE TITLE
New Release with fix for #227

### ISSUE THREAD

**Issue by phermsdorf** [ops4j/org.ops4j.pax.jdbc#232]
Hi,

i just stumbled about the ClassNotFound Exception mentioned in #227 . It seems to be fixed with #230 but there is no release with the fix included.
Would it be possible to make a release 1.5.2 with the fix included?

The workaround mentioned in https://github.com/ops4j/org.ops4j.pax.jdbc/issues/227#issuecomment-809081016 does not work for me. Karaf does not list any DataSourceFactory after these commands.

Thanks for your help.

Bye Peter

**Comment by grgrzybek** [comment]
Hello, thanks for reminder - I'll prepare a release by the end of this week.
WDYT @jbonofre ?

**Comment by phermsdorf** [comment]
@grgrzybek That would be great since we need the fix for a project.
Thanks!

**Comment by jbonofre** [comment]
@grgrzybek up to you, I can cut the release anytime if needed ;) Just let me know

**Comment by grgrzybek** [comment]
No need - I'll review the current state and release (checking pax.transx and pax.jms as well - but these probably don't need a release). thank, but I know you're busy ;)

**Comment by phermsdorf** [comment]
works for me.
Thank you very much!
