### ISSUE TITLE
Derby database inside Karaf based on pax-jdbc-derby - external access?

### ISSUE THREAD

**Issue by catshout** [ops4j/org.ops4j.pax.jdbc#254]
I did create a Derby database inside Karaf following https://karaf.apache.org/manual/latest/#_datasources_jdbc. Can this database be exposed for external access with a Derby Network Server?

P.S.: Is the Derby JDBC driver JDBC 4.0 compliant?

Best
Gerald

**Comment by grgrzybek** [comment]
Afaik, JDBC 4.0 was introduced in JDK 6, so quite long time ago. And afaik², Derby is the reference implementation of JDBC, so you should be fine ;).

About exposing Derby over TCP, I didn't try, but you could test with `url` property set to one of the TCP URIs.

`org.ops4j.pax.jdbc.derby.impl.TestDsf#testUrlBased` uses `jdbc:derby:target/test;create=true`, but you could try `jdbc:derby://host:port/databaseName;URLAttributes`.

**Comment by catshout** [comment]
Tx @grgrzybek.

I tried

```
jdbc:ds-create -dn derby -url "jdbc:derby://0.0.0.0:1527/test2;create=true" test2
```

and got

```
jdbc:ds-list
Name │ Service Id │ Product      │ Version               │ URL             │ Status
─────┼────────────┼──────────────┼───────────────────────┼─────────────────┼──────────────────────────────────────────────────────────────
...
431  │            │              │                       │                 │ Error No suitable driver

```

**Comment by grgrzybek** [comment]
For TCP URLs you have to use the `derby-native` driver:
```
karaf@root()> jdbc:ds-factories 
Name         │ Class                                  │ Version               │ Registration bundle
─────────────┼────────────────────────────────────────┼───────────────────────┼──────────────────────────────
derby-native │ org.apache.derby.jdbc.AutoloadedDriver │ 10.14.2000000.1828579 │ derby [62]
derby        │ org.apache.derby.jdbc.EmbeddedDriver   │                       │ org.ops4j.pax.jdbc.derby [64]
``

However even if `jdbc:ds-create -dn derby-native -url "jdbc:derby://0.0.0.0:1527/test2;create=true" test2` worked, it didn't create listener for the database. Pax JDBC is used to create connections (client side), not server listeners...
You'd have to create the instance yourself (blueprint, SCR, ...).

**Comment by catshout** [comment]
Doesn't work either ..

```@root()> jdbc:ds-create -dn derby-native -url "jdbc:derby://0.0.0.0:1527/test3;create=true" test3
karaf@root()> jdbc:ds-list
Name │ Service Id │ Product      │ Version               │ URL             │ Status
─────┼────────────┼──────────────┼───────────────────────┼─────────────────┼──────────────────────────────────────────────────────────────
...
432  │            │              │                       │                 │ Error null
```

Anyway, I'd address the issue with Derby as server instance inside Karaf at the Derby repo and/or Karaf repo.

**Comment by grgrzybek** [comment]
I got the same `null` - this is because `ds-list` tries to get connection metadata, but the connection wasn't established. This is a minor bug in Pax JDBC.

**Comment by catshout** [comment]
So the instance is there but not visible yet with `ds-list`? .. I tried `ds-info`, error as well.

**Comment by grgrzybek** [comment]
Creation of `javax.sql.DataSource` doesn't equal to create of database instance. You've created Derby Net DS, but it's pointing to URL at which nothing listens... You'd have to setup embedded Derby Database with network listener. That is NOT the responsibility of Pax JDBC.

The "memory" database URL is special (same for HSQLDB and H2) - you create Data source but also an in-memory database is created. That's not the behavior with _normal_ network (with host and port) JDBC URLs.

**Comment by grgrzybek** [comment]
> One last question, does Camel within Karaf leveraging the data sources created with pax-jdbc?

Assuming you Use Camel with Blueprint, you can simply _consume_ the published `javax.sql.DataSource` OSGi service.

**Comment by grgrzybek** [comment]
Closing as _explained_.
