### ISSUE TITLE
Can't create H2 database

### ISSUE THREAD

**Issue by jbonofre** [ops4j/org.ops4j.pax.jdbc#255]
When trying to create H2 database with pax-jdbc 1.5.3, the datasource fails with:

```
Error Syntax error in SQL statement "SET [*]CREATE true"; expected "@, AUTOCOMMIT, EXCLUSIVE, IGNORECASE, PASSWORD, SALT, MODE, DATABASE, COLLATION, CLUSTER, DATABASE_EVENT_LISTENER, ALLOW_LITERALS, DEFAULT_TABLE_TYPE, SCHEMA, CATALOG, SCHEMA_SEARCH_PATH, JAVA_OBJECT_SERIALIZER, IGNORE_CATALOGS, SESSION, TRANSACTION, TIME, NON_KEYWORDS, DEFAULT_NULL_ORDERING, LOG"; SQL statement: SET CREATE true [42001-210]
```

**Comment by grgrzybek** [comment]
The syntax has changed between H2 1.4.x and 2.1.x... We've updated it in #246 .
https://www.h2database.com/html/commands.html#set__ maybe?

**Comment by jbonofre** [comment]
Let me try, but it's via aries-jpa so not sure we have "control" at user side about SQL statements. I might have to update the statement in Aries JPA.

**Comment by jbonofre** [comment]
OK, it seems to be related to the upgrade to h2 from 1.4.200 to 2.1.210

**Comment by jbonofre** [comment]
Confirmed: if I downgrade pax-jdbc to h2 1.4.200, it works.

**Comment by jbonofre** [comment]
OK, with h2 2.x the URL should be updated to remote `create=true`
