### ISSUE TITLE
Documentation link is broken

### ISSUE THREAD

**Issue by driessamyn** [ops4j/org.ops4j.pax.jdbc#257]
The link to the documentation that is in the readme file (http://team.ops4j.org/wiki/display/PAXJDBC/Documentation) is broken.

Can the documentation be found somewhere else?

**Comment by grgrzybek** [comment]
The link should be https://ops4j1.jira.com/wiki/spaces/PAXJDBC/pages/23953600/Documentation
Though it's still very old documentation...

**Comment by grgrzybek** [comment]
The documentation link has been changed in 820b82be4aee9e6cdba884831f86d8a26a5734c0.
However for the documentation itself... Well - we there's some time ;)
