### ISSUE TITLE
invalid jmxName

### ISSUE THREAD

**Issue by sekaijin** [ops4j/org.ops4j.pax.jdbc#320]
Karaf 4
pax-jdbc 1.5.3

config file

     osgi.jdbc.driver.name=oracle
     pool=dbcp2
     url=jdbc:oracle:thin:@host:2600:FOO
     user=foo
     password=bar
     dataSourceName=foo

The ObjectName produced is 
     org.ops4j.pax.jdbc.pool.dbcp2:type=GenericObjectPool,name=pool
insted of
     org.ops4j.pax.jdbc.pool.dbcp2:type=GenericObjectPool,name=foo

but when the datasource is created by code like

      Properties dsProperties = new Properties();
      dsProperties.put("url", "jdbc:oracle:thin:@host:2600:FOO");
      dsProperties.put("user", "foo");
      dsProperties.put("password", "bar");
      dsProperties.put("dataSourceName", "foo");
      dsProperties.put("jdbc.pool.maxIdle", 4);
      dsProperties.put("jdbc.pool.maxTotal", 16);
      dsProperties.put("jdbc.pool.minIdle", 2);
      DataSource ds = pooledDSFactory.create(oracleDataSourcFactory, dsProperties);

The ObjectName produced is 
      org.ops4j.pax.jdbc.pool.dbcp2:type=GenericObjectPool,name=foo

**Comment by grgrzybek** [comment]
With b7eab7bae48c5a70835914628f8222eecd207e27, there was a weird change that `dataSourceName` property was removed during processing at some stage.

When you use `pooledDSFactory.create()` directly you don't loose it and Pax JDBC automatically does this:
```java
String dsName = (String) props.get(DataSourceFactory.JDBC_DATASOURCE_NAME);
if (dsName != null) {
    poolProps.put("jmxNamePrefix", dsName);
}
```

`jmxNamePrefix` is a bean property of `org.apache.commons.pool2.impl.GenericObjectPoolConfig` object.

To make it work with config-based approach, you have to use this property instead:
```
pool.jmxNamePrefix = foo
```

you'll get proper:
![image](https://github.com/ops4j/org.ops4j.pax.jdbc/assets/306565/7b79f966-a193-46d0-b0cf-913249fd26b1)

**Comment by grgrzybek** [comment]
Also #165 (PAXJDBC-101) made `dataSourceName` a _non-forwardable_ property, which should be removed when passing to bean configuration method.

That's why you have to use `pool.jmxNamePrefix`
